name: wick
base: core20
version: git
compression: lzo
summary: WAMP In Command-line
description: |
  WAMP In Command-line

grade: stable
confinement: strict

parts:
  wick:
    plugin: go
    source: .

apps:
  wick:
    command: bin/wick
    plugs:
      - network
