name: wick
base: core20
version: git
compression: lzo
summary: WAMP In Command-line
description: WAMP In Command-line

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: arm64
    run-on: arm64

grade: stable
confinement: strict

parts:
  wick:
    plugin: go
    source: .

apps:
  wick:
    command: bin/wick
    plugs:
      - network
