name: wick
base: core20
version: git
compression: lzo
summary: WAMP In command-line
description: WAMP In command-line

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: arm64
    run-on: arm64

grade: stable
confinement: classic

parts:
  wick:
    plugin: go
    source: .
    override-prime: |
      snapcraftctl prime
      cp $SNAPCRAFT_PART_SRC/wick_bash_autocomplete.sh $SNAPCRAFT_PRIME/

apps:
  wick:
    command: bin/wick
    completer: wick_bash_autocomplete.sh
    plugs:
      - network
