name: build-arm64-snap

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: self-hosted

    steps:
      - name: checkout git repository
        uses: actions/checkout@v2

      - name: build snap
        run: snapcraft --use-lxd

      - name: copy build artifacts
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          rm -rf /tmp/ci-artifacts-arm64
          mkdir -p /tmp/ci-artifacts-arm64
          cp $(realpath wick_*.snap) /tmp/ci-artifacts-arm64
